import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
const inter = Inter({ subsets: ["latin"] });
const GlobalContext = dynamic(() => import("./components/globalContext"), {
  ssr: false,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-poppins dark:bg-[#060912]">
        <GlobalContext>
          <Navbar />
          {children}
          <Footer />
        </GlobalContext>
      </body>
    </html>
  );
}
