import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToggleButton from "./components/toggleButton";
import NavButtons from "./components/navButtons";
import dynamic from "next/dynamic";
// import GlobalContext from "./components/globalContext";
const inter = Inter({ subsets: ["latin"] });
const GlobalContext = dynamic(() => import("./components/globalContext"), {
  ssr: false,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <GlobalContext>
          <div className="py-8 px-8">
            <nav
              className="flex justify-between mx-auto rounded-md max-w-4xl md:p-8"
              style={{ alignItems: "center" }}
            >
              <ToggleButton />
              <NavButtons />
            </nav>
          </div>
          {children}
        </GlobalContext>
      </body>
    </html>
  );
}
