import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToggleButton from "./components/toggleButton";
import NavButtons from "./components/navButtons";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <div className="lg:my-8">
          <nav
            className="flex justify-between mx-auto rounded-md max-w-4xl lg:p-8"
            // style={{ maxWidth: "830px" }}
          >
            <ToggleButton />
            <NavButtons />
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
